version: '3'

services:
  postgresql-service:
    image: postgres:15.3
    container_name: talento-tech
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=heart-db
    volumes:
      - ./postgres:/var/lib/postgresql/data